### ISSUE TITLE
implement authentication service with firebase

### ISSUE THREAD

**Issue by andrelas1** [bitfindr/bitfindr#19]

**Comment by pranay414** [comment]
@andrelas1 I want to work on this, can you provide more info about this?

**Comment by kshaaban-** [comment]
Auth Provider methods:
- [x] checkAuthState (introduced in #36)
- [x] signup (introduced in #36)
- [ ] signin (PR #39)
- [ ] signout

Can anyone think of more methods that might need to live in `AuthProvider` for now?
