### ISSUE TITLE
Add user register page

### ISSUE THREAD

**Issue by andrelas1** [bitfindr/bitfindr#20]

**Comment by kshaaban-** [comment]
@luisguilhermemaia 
I was going to jump on this issue, but @yannbf mentioned that you had already started working on it.

I'm not sure what Auth Providers are configured on the Firebase project, but I was planning on implementing a simple registration page consisting of a form capturing a new user's email/password before sending it off to Firebase. Of course with proper handling of any auth errors. And necessary refactoring to `app.component` so that it loads the correct `rootPage` based on current auth state.

**Comment by luisguilhermemaia** [comment]
Hi guys
I am now working right now on the prototype of the Register Page...
here is a preview:
<img width="349" alt="captura de tela 2017-10-21 as 14 07 39" src="https://user-images.githubusercontent.com/16075854/31854782-6e09eab0-b675-11e7-8215-86eccaf5480d.png">

**Comment by kshaaban-** [comment]
You can DM me on Twitter (@KhalShaa) and we can share skype info (or any other means of communication you prefer)

Meanwhile, The only issue I see with the signup form is that [Firebase User](https://firebase.google.com/docs/reference/js/firebase.User) doesn't store first/last names.

We'd need to save user profiles at a separate reference point in firebase, something like `/profile/${uid}/` where we can capture first/last name, and any other profile data we might need for this app. Perhaps this could be the second step after registration?

I'll go ahead and send a PR to your branch with an implementation!

**Comment by yannbf** [comment]
Yes @kshaaban-, I believe it is best to create a separate structure for the user profile. This may be handy:

```
                let { displayName, email, photoURL } = firebaseData.providerData[0];

                userObject = {
                    uid: uid,
                    registeredDate: Date.now(),
                    name: displayName,
                    firstName: displayName.match(/^(\S+)\s(.*)/).slice(1)[0],
                    lastName: displayName.match(/^(\S+)\s(.*)/).slice(1)[1],
                    email: email,
                    socialPhotoURL: photoURL,
                    whateverOtherAtributtes: { }
                };

                this.af.database.list('userProfile').update(uid, userObject).then(() => true);
```

**Comment by yannbf** [comment]
There's also [our gitter channel](https://gitter.im/bitfindr/Lobby) that is not very active yet since we are not many yet.
if you enter there you'll see a lot of portuguese messages, but we all speak english.
