### ISSUE TITLE
Implement Login Page

### ISSUE THREAD

**Issue by andrelas1** [bitfindr/bitfindr#3]

**Comment by kshaaban-** [comment]
I'd like to work on both, this and #20

**Comment by yannbf** [comment]
Hey @kshaaban- , Thanks a lot for your interest in contributing to this repo! I believe @luisguilhermemaia is already working on this, but this issue wasn't updated. Anyhow, I'd love to see what you could bring on this feature. Perhaps you could talk to @luisguilhermemaia and you both come to a good result :D

**Comment by luisguilhermemaia** [comment]
Hi guys
I am now working right now on the prototype of the Login Page...
here is a preview:
<img width="347" alt="captura de tela 2017-10-21 as 13 59 12" src="https://user-images.githubusercontent.com/16075854/31854011-dc390dca-b668-11e7-8bd8-8632d57bbc29.png">


@kshaaban-  very nice! What's the best way for us to discuss?
