### ISSUE TITLE
Implement FacebookAuthProvider

### ISSUE THREAD

**Issue by kshaaban-** [bitfindr/bitfindr#40]
Use native cordova plugins to authenticate via facebook, then pass auth tokens to firebase for app authentication

**Comment by kshaaban-** [comment]
See [this branch](https://github.com/bitfindr/bitfindr/tree/feature/facebook-auth) for implementation.

The implementation is still un-tested.

- Need Facebook app name to be set in `package.json` and `config.xml` as configured on facebook developer dashboard.
- Test Facebook login on a device.

**Comment by yannbf** [comment]
Amazing! Just amazing 💃 

I'll take a look at it and add the needed info later on.
