### ISSUE TITLE
Add main colors - app theme

### ISSUE THREAD

**Issue by andrelas1** [bitfindr/bitfindr#5]

**Comment by yannbf** [comment]
Amazing tool to give us choices to discuss about: http://colorhunt.co/

**Comment by andrelas1** [comment]
I will submit a PR soon about the starting colors of the app. The color palette that I'm enjoying with a dark theme is:

http://colorhunt.co/c/92753

The dark colors (gradient) are: #023E4A #162221

Inspiration is coming from:
https://dribbble.com/shots/3544732-Website-Homepage-for-Multi-Profile-Bitcoin-Desktop-App
https://dribbble.com/shots/3602881-Teambrella-Home-screen
https://dribbble.com/shots/3088179-Bitcoin-wallet

**Comment by andrelas1** [comment]
Issue resolved
